### PR TITLE
use dependency injection instead of facade

### PR DESCRIPTION
**Pull request by tzookb**

### CODE REVIEW

**Comment by maknz** [comment]
Cool idea. Can you fix the whitespace (2 spaces for indentation) and make sure there's a newline between method calls on the L4 provider, then [squash your commits](http://davidwalsh.name/squash-commits-git).

**Comment by tzookb** [comment]
Sure no problem,  I did it with my tablet :)  give me 2 hours

**Comment by tzookb** [comment]
I fixed that, the indentation looks good in my phpstorm, but here it has an extra tab, but it looks good, and in one commit.

**Comment by maknz** [comment]
That's fine, I'll fix it up afterward. I'll give this a test tonight and merge if all is well.

**Comment by tzookb** [comment]
thanks, you will save me that line of code in 3 projects :+1:

**Comment by maknz** [comment]
Thanks, tests fine in L4 and L5. Released in v1.3.0. Thanks :+1:

**Pull request merged**
