### PR TITLE
NexySlackBundle documentation and suggestion

### LINKED ISSUE #37: Support for Symfony bundle
I see you have Laravel native support.

Would you accept a PR for Symfony bundle support?

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Closes #37.

As discussed on the related issue, I worked for a Symfony integration on an external bundle.

The basics are here, the bundle is stable and ready to use, so I think it's time to link it on your documentation. ;-)

Feel free to comment if you want to review some things before merge. :+1: 

Official announcement: https://twitter.com/soullivaneuh/status/707244694540001280

### CODE REVIEW

**Comment by maknz** [comment]
I've added the composer suggest on master, along with a mention beside the Laravel support line. If that's all fine, go ahead and close this :+1:

**Comment by Soullivaneuh** [comment]
I think the Symfony part on the documentation would be better to guide developers. As you wish. :+1: 

Another things that would be great is to add the Symfony keywords on `composer.json` for more reliable search.

**Comment by maknz** [comment]
Probably best to add the Symfony keywords to your package so users will be lead there instead.

Let me know if you're happy and we can close this.

**Comment by Soullivaneuh** [comment]
This is your decision. But I still think a reference on the documentation would be even easier for developers.

**Pull request closed without merging**
