### PR TITLE
added Attachment Actions (buttons) with confirmations

### PR DESCRIPTION
**Pull request by janek2012**
Slack added buttons to attachments:
https://slackhq.com/get-more-done-with-message-buttons-5fa5b283a59
https://api.slack.com/docs/message-buttons

### CODE REVIEW

**Comment by maknz** [comment]
This looks really good, thanks! I'll have a play this weekend and get this merged. Fairly happy with the classes/API decided on.

**Comment by maknz** [comment]
@janek2012 I'm happy to get this merged in. This PR doesn't deal with responding to action buttons, but I'm happy to work on that and PR something.

**Comment by funkytaco** [comment]
Can we please get this on Packagist/Composer? I'd like to use this. Thanks!

**Comment by maknz** [comment]
It's development code right now, I haven't actually used it yet. You can require dev-master if you wanna try it out (or a specific commit).

**Comment by funkytaco** [comment]
Thank you. This works perfectly. Please let us know once it's in the public release, so I can switch back from dev-master.

**Comment by maknz** [comment]
Hey there, at the present I'm really strapped for time and can't dedicate the requisite time to produce a stable release. I would encourage anyone keen to maintain a fork.

**Pull request merged**
