### PR TITLE
Add image_url to attachment

### PR DESCRIPTION
**Pull request by Leenug**
Added the ability to embed an image directly into an attachment, as per: https://api.slack.com/docs/attachments

### CODE REVIEW

**Comment by maknz** [comment]
This looks really good, thanks! I'll give it a quick test over the weekend and merge.

You may need to modify the attachment tests (especially the ones dealing with the full payload sent to slack) to include the new field. If you can do that, and [squash the commits into one](http://davidwalsh.name/squash-commits-git), this should be :+1:

**Comment by Leenug** [comment]
Apologies for the delay, should be good to go now :)

**Comment by chekalskiy** [comment]
Great, when it will be merged, @maknz?

**Comment by maknz** [comment]
I haven't had a chance to try it out just yet, but it looks pretty good so I think we can just merge it. Will do soon.

**Comment by chekalskiy** [comment]
I've tested already, all right! :ok_hand:

**Comment by maknz** [comment]
Sweet, thanks all.

**Pull request merged**
